name: Delete Old Meetings

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  delete-old-meetings:
    runs-on: ubuntu-latest

    steps:
      - name: Call API to delete old meetings
        run: |
          curl --request POST \
          --url 'https://ktt-api.onrender.com/api/meetings/delete-old-meetings'
