name: Wake up backend

on:
  schedule:
    - cron: "0,10,20,30,40,50 * * * *"
  workflow_dispatch:

jobs:
  wake-up-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Make GET request
        run: |
          curl --request GET \
          --url 'https://ktt-api.onrender.com/api/addresses'
